---

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  become: yes

- name: restart munge
  service:
    name: munge
    state: restarted
  become: yes

- name: restart slurmctld
  service:
    name: slurmctld
    state: restarted
  become: yes

- name: restart nfs-kernel-server
  service:
    name: nfs-kernel-server
    state: restarted
  become: yes

- name: restart linuxboot-ci-api
  service:
    name: linuxboot-ci-api
    state: restarted
  become: yes
