---

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  become: yes

- name: restart munge
  service:
    name: munge
    state: restarted
  become: yes

- name: restart slurmctld
  service:
    name: slurmctld
    state: restarted
  become: yes
