---

- import_tasks: dhcp.yml
  tags:
    - dhcp
  when: dhcp_enabled

- import_tasks: munge.yml
  tags:
    - munge

- import_tasks: slurm.yml
  tags:
    - slurm

- import_tasks: scripts.yml
  tags:
    - scripts
