---

- import_tasks: dhcp.yml
  tags:
    - dhcp
  when: dhcp['enabled']

- import_tasks: munge.yml
  tags:
    - munge

- import_tasks: slurm.yml
  tags:
    - slurm

- import_tasks: scripts.yml
  tags:
    - scripts

- import_tasks: nfs.yml
  tags:
    - nfs

- import_tasks: api.yml
  tags:
    - api
