---

- import_tasks: packages.yml
  tags:
    - packages

- import_tasks: munge.yml
  tags:
    - munge

- import_tasks: slurm.yml
  tags:
    - slurm

- import_tasks: kvm.yml
  tags:
    - kvm

- import_tasks: nfs.yml
  tags:
    - nfs
