---

- name: Install NFS client
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  with_items:
    - nfs-common

- name: Ensure directory for job data exists
  file:
    path: "/var/lib/ci"
    state: directory
    mode: 0755
    owner: "linuxboot"
    group: "ci"
  become: yes

- name: Mount NFS Folder
  mount:
    path: /var/lib/ci
    src: "{{ slurm['controller']['listen_addr'] }}:/var/lib/ci"
    fstype: nfs
    opts: auto,nofail,noatime,nolock,intr,tcp,actimeo=1800
    state: mounted
  become: yes
